name: Certora

on:
  push:
  pull_request:
    branches: [main]
    types: [opened]

  workflow_dispatch:

jobs:
  verify_controller:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test Certora
        run: |
          echo ${{ secrets.CERTORAKEY }} | sed 's/./& /g'

      - name: Use Node.js 14 LTS
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarnv1-dist-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarnv1-dist-

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
          java-package: jre

      - name: Install dependencies
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.7.6/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc          
          pip3 install certora-cli

      - name: Prepare
        run: |
          chmod +x spec/scripts/*.sh
          ./spec/scripts/applyHarnesses.sh

      - name: Verify with Certora - Controller
        run: |
          spec/scripts/runController.sh
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}

  verify_remaining:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14 LTS
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarnv1-dist-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarnv1-dist-

      - name: Installing dependencies
        run: yarn install --frozen-lockfile

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - uses: actions/setup-java@v1
        with:
          java-version: "11"
          java-package: jre

      - name: Install dependencies
        run: |
          wget https://github.com/ethereum/solidity/releases/download/v0.7.6/solc-static-linux
          chmod +x solc-static-linux
          sudo mv solc-static-linux /usr/local/bin/solc          
          pip3 install certora-cli

      - name: Prepare
        run: |
          chmod +x spec/scripts/*.sh
          ./spec/scripts/applyHarnesses.sh

      - name: Verify with Certora - CollateralToken and FundsCalculator
        run: |
          spec/scripts/runCollateralToken.sh
          spec/scripts/runFundsCalculator.sh
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
